'use client';
import type { ColumnDef } from '@tanstack/react-table';
import Link from 'next/link';
import { BiEdit, BiTrash } from 'react-icons/bi';
import type { Post } from '@types';

export const PostColumns: ColumnDef<Post>[] = [
    {
        header: 'id',
        accessorKey: 'id',
    },
    {
        header: 'title',
        accessorKey: 'title',
        accessorFn: (post) => {
            return post.title.length > 30 ? `${post.title.slice(0, 28)}...` : post.title;
        },
    },
    {
        header: 'tags',
        accessorKey: 'tags',
        accessorFn: (post) => {
            return post.tags.map((tag) => {
                return tag.length > 15 ? `${tag.slice(0, 13)}...` : tag;
            });
        },
        cell: ({ row }) => {
            return row.original.tags.slice(0, 2).map((tag) => {
                return (
                    <span className='border-[1px] ml-1 border-primary rounded-full px-2 gap-2 w-fit' key={tag} title={tag}>
                        {tag.length > 10 ? `${tag.slice(0, 8)}...` : tag}
                    </span>
                );
            });
        },
    },
    {
        header: 'liked',
        accessorKey: 'likes',
    },
    {
        header: 'author',
        accessorKey: 'author',
    },
    {
        header: 'createdAt',
        accessorKey: 'created_at',
        accessorFn: (post) => post.created_at.toISOString().slice(0, 10),
    },
    {
        header: 'last modified',
        accessorKey: 'updated_at',
        accessorFn: (post) => post.updated_at.toISOString().slice(0, 10),
    },
    {
        header: 'Actions',
        cell: (post) => {
            return (
                <div className='flex gap-1 place-items-center'>
                    <Link className='text-primary' href={`dashboard/posts?edit=${post.cell.row.original.id}`}>
                        <BiEdit size={22} />
                    </Link>
                    <Link className='text-primary' href={`dashboard/posts?delete=${post.cell.row.original.id}`}>
                        <BiTrash size={22} />
                    </Link>
                </div>
            );
        },
    },
];

export const posts: Post[] = [
    {
        id: '1',
        title: 'Exploring the Wonders of Nature',
        body: "Nature never ceases to amaze us with its breathtaking beauty. From towering mountains to serene lakes, let's embark on a journey to discover the wonders of the natural world.",
        tags: ['nature', 'exploration', 'adventure'],
        author: 'NatureEnthusiast87',
        likes: 125,
        comments: 'Join the conversation!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '2',
        title: 'The Art of Cooking: A Culinary Adventure',
        body: "Delight your taste buds with culinary masterpieces from around the globe. From savory dishes to delectable desserts, let's embark on a flavorful journey through the world of cooking.",
        tags: ['cooking', 'food', 'culinary'],
        author: 'ChefExtraordinaire',
        likes: 98,
        comments: 'Share your favorite recipes!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '3',
        title: 'Unlocking the Power of Technology',
        body: 'Innovation knows no bounds in the world of technology. Join us as we explore the latest advancements, from artificial intelligence to virtual reality, and their impact on society.',
        tags: ['technology', 'innovation', 'science'],
        author: 'TechInnovator22',
        likes: 203,
        comments: 'Discuss the future of tech!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '4',
        title: 'Mindfulness: Finding Peace in the Present Moment',
        body: "Amidst the chaos of modern life, practicing mindfulness offers a path to inner peace and tranquility. Let's explore mindfulness techniques and their profound impact on mental well-being.",
        tags: ['mindfulness', 'wellness', 'meditation'],
        author: 'ZenSeeker',
        likes: 150,
        comments: 'Share your mindfulness journey!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '5',
        title: 'Artificial Intelligence: Shaping the Future of Humanity',
        body: 'From self-driving cars to personalized recommendations, artificial intelligence is revolutionizing every aspect of our lives. Join the conversation on how AI is shaping the future of humanity.',
        tags: ['artificial intelligence', 'technology', 'future'],
        author: 'AIEnthusiast',
        likes: 302,
        comments: 'Discuss the ethical implications!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '6',
        title: 'Fitness & Wellness: A Journey to Healthier Living',
        body: "Embark on a journey to achieve a healthier lifestyle through fitness and wellness. From workout routines to nutritious recipes, let's support each other on the path to well-being.",
        tags: ['fitness', 'wellness', 'health'],
        author: 'FitLifeGuru',
        likes: 180,
        comments: 'Share your fitness goals!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '7',
        title: 'Space Exploration: Journey to the Unknown',
        body: "Discover the mysteries of the cosmos as we embark on a journey through space exploration. From distant galaxies to exoplanets, let's unravel the secrets of the universe.",
        tags: ['space', 'exploration', 'cosmos'],
        author: 'SpaceExplorer99',
        likes: 250,
        comments: 'Join us in our quest for knowledge!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '8',
        title: 'The Power of Positivity: Embracing Optimism',
        body: "Embrace the power of positivity and transform your life. Let's explore the benefits of optimism and how it can lead to greater happiness and success.",
        tags: ['positivity', 'optimism', 'self-improvement'],
        author: 'PositiveVibesOnly',
        likes: 210,
        comments: 'Share your uplifting stories!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '9',
        title: 'Environmental Conservation: Preserving Our Planet',
        body: "Join the movement to protect our planet for future generations. From reducing plastic waste to promoting renewable energy, let's take action for environmental conservation.",
        tags: ['environment', 'conservation', 'sustainability'],
        author: 'GreenActivist',
        likes: 180,
        comments: 'Share your eco-friendly tips!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
    {
        id: '10',
        title: 'Exploring World Cultures: Celebrating Diversity',
        body: "Dive into the rich tapestry of world cultures and traditions. Let's celebrate diversity and learn from each other's customs, languages, and heritage.",
        tags: ['culture', 'diversity', 'heritage'],
        author: 'CulturalExplorer',
        likes: 220,
        comments: 'Share your cultural experiences!',
        created_at: new Date('2024-05-09'),
        updated_at: new Date('2024-05-09'),
    },
];
